// Generated by CoffeeScript 1.6.3
/*global app, Router*/

(function(app, Router) {
  'use strict';
  var router;
  router = new Router;
  ['all', 'active', 'completed'].forEach(function(visibility) {
    return router.on(visibility, function() {
      return app.visibility = visibility;
    });
  });
  router.configure({
    notfound: function() {
      window.location.hash = '';
      return app.visibility = 'all';
    }
  });
  return router.init();
})(app, Router);
