var directives = module.exports = Object.create(null)

directives.text     = require('./text')
directives.html     = require('./html')
directives.attr     = require('./attr')
// directives.show     = require('./show')
// directives['class'] = require('./class')
// directives.ref      = require('./ref')
// directives.cloak    = require('./cloak')
// directives.on       = require('./on')
// directives.repeat   = require('./repeat')
// directives.model    = require('./model')
// directives['if']    = require('./if')
// directives['with']  = require('./with')
// directives.html     = require('./html')
// directives.style    = require('./style')
// directives.partial  = require('./partial')
// directives.view     = require('./view')